services:
  player1:
    build: ./blue
    tty: true
    ports:
      - "21022:22"
      - "21080:80"

  player2:
    build: ./blue
    tty: true
    ports:
      - "22022:22"
      - "22080:80"
  
  player3:
    build: ./blue
    tty: true
    ports:
      - "23022:22"
      - "23080:80"
  
  player4:
    build: ./blue
    tty: true
    ports:
      - "24022:22"
      - "24080:80"
  
  player5:
    build: ./blue
    tty: true
    ports:
      - "25022:22"
      - "25080:80"
  
  player6:
    build: ./blue
    tty: true
    ports:
      - "26022:22"
      - "26080:80"
  
  player7:
    build: ./blue
    tty: true
    ports:
      - "27022:22"
      - "27080:80"

  red:
    build: ./red
    tty: true
    ports:
      - "5555:5555"

  score-server:
    build: ./score-server
    tty: true
    ports:
      - "3000:3000"