services:
  container1:
    build: ./blue
    tty: true
    ports:
      - "21022:22"
      - "21080:80"

  red:
    build: ./red
    tty: true
    ports:
      - "5555:5555"

  score-server:
    build: ./score-server
    tty: true
    ports:
      - "3000:3000"